//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaBanco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentaCliente()
        {
            this.transaccion = new HashSet<transaccion>();
        }
    
        public int id { get; set; }
        public string numcuenta { get; set; }
        public Nullable<int> Cliente { get; set; }
        public Nullable<long> saldo { get; set; }
        public Nullable<int> Banco { get; set; }
    
        public virtual Banco Banco1 { get; set; }
        public virtual Cliente Cliente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaccion> transaccion { get; set; }
    }
}
