//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaBanco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaccion
    {
        public int id { get; set; }
        public Nullable<int> idcliente { get; set; }
        public Nullable<int> idcuenta { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> valor { get; set; }
        public Nullable<int> operacion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual CuentaCliente CuentaCliente { get; set; }
    }
}
