//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaBanco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_cuentacliente
    {
        public int id { get; set; }
        public string numcuenta { get; set; }
        public Nullable<int> Cliente { get; set; }
        public Nullable<long> saldo { get; set; }
        public Nullable<int> Banco { get; set; }
    }
}
